### ISSUE TITLE
tsconfig target is out of sync w/official plugin

### ISSUE THREAD

**Issue by pjeby** [THeK3nger/obsidian-plugin-template#1]
Hey, just a heads-up.  The tsconfig should target at least es6 (and pref. es2018), as in a future version Obsidian will require all plugins to use real es6 classes instead of emulations generated by Babel or Typescript.

**Comment by THeK3nger** [comment]
Thank you for the heads-up! Update in 37c3fedb8a5bf59c4b2467a9e2da068a544e16e1
