### ISSUE TITLE
Update dependencies and configuration

### ISSUE THREAD

**Issue by lishid** [THeK3nger/obsidian-plugin-template#2]
There's been a few changes to the official sample plugin. Would appreciate an update to this repo so new plugin developers start off with an up-to-date template.

https://github.com/obsidianmd/obsidian-sample-plugin/commits/master

(Also I'd recommend sticking to ES6 instead of ES2018 just because some mobile devices are no longer getting updates from the 2017-2018 era).

**Comment by THeK3nger** [comment]
Done. It was in my list of things to do for a while. Thank you for nudging me into finally do it. ;)
